name: kicadbom2spec
version: "3-snap1"
summary: Построение перечней элементов для схем выполненных в САПР KiCad.
description: |
  Приложение kicadbom2spec создает файл перечня элементов в виде таблицы *.ods в
  формате Open Document Format, оформленной согласно требованиям ЕСКД, используя
  файл схемы в формате KiCad Schematic. Также позволяет редактировать поля
  элементов схем и библиотек.
confinement: classic
grade: devel

apps:
  kicadbom2spec:
    command: usr/share/kicadbom2spec/kicadbom2spec.pyw
    plugs: [home, unity7]

parts:
  kicadbom2spec:
    plugin: dump
    source: lp:kicadbom2spec
    organize:
      '*.py': usr/share/kicadbom2spec/
      '*.pyw': usr/share/kicadbom2spec/
      CHANGELOG: usr/share/kicadbom2spec/
      COPYING: usr/share/kicadbom2spec/
      README: usr/share/kicadbom2spec/
      bitmaps: usr/share/kicadbom2spec/bitmaps/
      doc/images: usr/share/kicadbom2spec/doc/images/
      doc/user_manual.html: usr/share/kicadbom2spec/doc/
      pattern.ods: usr/share/kicadbom2spec/
      sample: usr/share/kicadbom2spec/sample/
      settings.ini: usr/share/kicadbom2spec/
      version: usr/share/kicadbom2spec/
    stage:
      - -archlinux
      - -checkinstall
      - -doc
      - -gui.fbp
      - -windows

  deps:
    plugin: nil
    stage-packages:
      - python2.7
      - python-wxgtk3.0
      - python-odf
    organize:
      usr/lib/wx/python/wx3.0.pth: usr/lib/python2.7/dist-packages/wx.pth
